### ISSUE TITLE
List color does not update when removing cards from a list

### ISSUE THREAD

**Issue by rumenavramov** [NateHark/TrelloWIPLimits#10]
Thanks for the great add-on!
I am using it in Firefox and I noticed that list colour does not get updated when I move cards using the "Move" function from the menu; drag-n-drop works fine.
Also, when I add new cards to a list with a limit and I hit the limit, the colour changes to red instead of orange.

**Comment by NateHark** [comment]
I'm glad you're enjoying the add-on. Thanks for the report. I'll investigate.

**Comment by rumenavramov** [comment]
Thanks for fixing it so fast! I just updated the add-on it's much better :)
